Repository SzFMV2018-Osz/AutomatedCar-B, pull requests merged in 2018-10, with the labels that each got.

#93 Dashboard Manager system component
  src/main/java/hu/oe/nik/szfmv/Main.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/AutomatedCar.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/bus/VirtualFunctionBus.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/DashboardPacket.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/interfaces/IReadOnlyDashboardPacket.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/DashboardManager.java
  src/main/java/hu/oe/nik/szfmv/visualization/Dashboard.java
  src/main/java/hu/oe/nik/szfmv/visualization/elements/IndexArrow.java
Labels: enhancement

#107 Debug section display on the dashboard
  src/main/java/hu/oe/nik/szfmv/Main.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/AutomatedCar.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/DashboardManager.java
  src/main/java/hu/oe/nik/szfmv/visualization/Dashboard.java
  src/main/java/hu/oe/nik/szfmv/visualization/elements/DebugSection.java
  src/main/java/hu/oe/nik/szfmv/visualization/elements/PedalBar.java
  src/main/resources/config.toml
  src/test/java/hu/oe/nik/szfmv/automatedcar/bus/packets/GraduallyChangeableTest.java
Labels: enhancement

#116 Autó rotáció implementálása.
  src/main/java/hu/oe/nik/szfmv/visualization/CourseDisplay.java
Labels: urgent

#118 Scalefactor módosítása, üzemi scalere optimalizálása
  src/main/java/hu/oe/nik/szfmv/visualization/CourseDisplay.java
Labels: urgent

#119 Vizualizáció
  src/main/java/hu/oe/nik/szfmv/Main.java
  src/main/java/hu/oe/nik/szfmv/environment/World.java
  src/main/java/hu/oe/nik/szfmv/environment/WorldObject.java
  src/main/java/hu/oe/nik/szfmv/visualization/CourseDisplay.java
  src/main/java/hu/oe/nik/szfmv/visualization/Dashboard.java
  src/main/java/hu/oe/nik/szfmv/visualization/Gui.java
  src/main/java/hu/oe/nik/szfmv/visualization/GuiAdapter.java
  src/main/java/hu/oe/nik/szfmv/visualization/ReferencePointClass.java
  src/main/java/hu/oe/nik/szfmv/visualization/ReferencePointsXMLReadClass.java
  src/main/resources/reference_points.xml
Labels: user story

#156 Team b3 feature sensor packets
  src/main/java/hu/oe/nik/szfmv/automatedcar/AutomatedCar.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/bus/VirtualFunctionBus.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/DisplayableSensorPacket.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/SensorPacket.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/interfaces/IReadonlyDisplayableSensorPacket.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/interfaces/IReadonlySensorPacket.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/sensor/SensorType.java
  src/main/java/hu/oe/nik/szfmv/common/enums/Coordinate.java
  src/test/java/hu/oe/nik/szfmv/automatedcar/bus/packets/DisplayableSensorPacketTest.java
  src/test/java/hu/oe/nik/szfmv/automatedcar/bus/packets/SensorPacketTest.java
Labels: enhancement
